version: '2'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - './:/var/www'
      - './site.conf:/etc/nginx/conf.d/default.conf'

  php:
    build: php
    volumes:
      - './:/var/www'
